=== repometric/linterhub-cli/src/hub/.schema/engine.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This document describes the engine definition",
    "description": "The meta information of engine",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The engine name"
        },
        "description": {
            "type": "string",
            "description": "The engine description"
        },
        "url": {
            "type": "string",
            "description": "The engine url or homepage",
            "format": "uri"
        },
        "version": {
            "description": "The engine version (expected)",
            "type": "object",
            "properties": {
                "package": {
                    "type": "string",
                    "description": "Package version"
                },
                "local": {
                    "type": "string",
                    "description": "Local version"
                }
            }
        },
        "languages": {
            "type": "array",
            "description": "The list of supported languages",
            "items": {
                "type": "string",
                "enum": [
                    "coffeescript",
                    "css",
                    "html",
                    "javascript",
                    "json",
                    "jsx",
                    "sass",
                    "typescript"
                ]
            }
        },
        "extensions": {
            "type": "array",
            "description": "Common file extensions parsed by engine",
            "items": {
                "type": "string"
            }
        },
        "license": {
            "type": "string",
            "description": "The engine license",
            "enum": [
                "Unknown",
                "AGPL-3.0",
                "Apache-2.0",
                "MIT"
            ]
        },
        "requirements": {
            "type": "array",
            "description": "The engine requirements",
            "items": {
                "$ref": "#/definitions/requirement"
            }
        },
        "areas": {
            "type": "array",
            "description": "The engine areas",
            "items": {
                "type": "string",
                "enum": [
                    "code simplification",
                    "commented code",
                    "complexity",
                    "documentation",
                    "duplication",
                    "formatting",
                    "grammar",
                    "memory leak",
                    "security",
                    "simplification",
                    "smell",
                    "spelling",
                    "syntax",
                    "undefined element",
                    "unreachable code",
                    "unused code"
                ]
            }
        },
        "prefix": {
            "type": "string",
            "description": "Prefix in terminal (normally engine name)"
        },
        "postfix": {
            "type": "string",
            "description": "Postfix in terminal (normaly post processor)"
        },
        "optionsDelimiter": {
            "type": "string",
            "description": "Delimiter for options (space by default)",
            "default": " "
        },
        "successCode": {
            "type": "integer",
            "description": "Success exit code"
        },
        "active": {
            "type": "boolean",
            "description": "A value indicating whether linter is active",
            "default": true
        },
        "defaults": {
            "type": "object",
            "description": "The default configuration of engine. This property is specific for each engine"
        },
        "stdin":{
            "type": "object",
            "description": "Support of stdin analyze",
            "properties": {
                "available": {
                    "type": "boolean",
                    "description": "Supports stdin or not"
                },
                "customCommand": {
                    "type": "string",
                    "description": "Custom command to path all variables for stdin analyze"
                }
            }
        }
    },
    "required": [
        "name",
        "description",
        "languages",
        "license",
        "areas",
        "stdin"
    ],
    "definitions": {
        "requirement": {
            "type": "object",
            "description": "The engine dependency",
            "properties": {
                "manager": {
                    "type": "string",
                    "description": "The manager for dependency",
                    "enum": [
                        "system",
                        "url",
                        "composer",
                        "gem",
                        "npm",
                        "pip"
                    ]
                },
                "package": {
                    "type": "string",
                    "description": "The package name"
                }
            }
        }
    }
}

=== repometric/linterhub-cli/src/hub/csslint/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "csslint",
    "description": "Automated linting of Cascading Stylesheets",
    "url": "http://csslint.net",
    "languages": [
        "css"
    ],
    "extensions": [
        "*.css"
    ],
    "license": "MIT",
    "areas": [
        "syntax",
        "code simplification"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "csslint"
        }
    ],
    "version": {
        "local": "v1.0.5",
        "package": "1.0.5"
    },
    "postfix": " | node file://{schema}/csslint/reporter.js",
    "prefix": "node file://{schema}/csslint/prefix.js ",
    "optionsDelimiter": "=",
    "defaults": {
        "": "./",
        "--format": "compact"
    },
    "stdin":
    {
        "available": false
    }
}

=== repometric/linterhub-cli/src/hub/jshint/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "jshint",
    "description": "JSHint is a tool that helps to detect errors and potential problems in your JavaScript code",
    "url": "http://jshint.com",
    "languages": [
        "javascript"
    ],
    "extensions": [
        "*.js"
    ],
    "license": "MIT",
    "areas": [
        "syntax",
        "formatting",
        "complexity",
        "unused code"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "jshint"
        }
    ],
    "version": {
        "local": "jshint v2.9.5",
        "package": "2.9.5"
    },
    "defaults": {
        "": "./",
        "--reporter": "file://{schema}/jshint/reporter.js"
    },
    "stdin":
    {
        "available": true,
        "customCommand": "--filename=file://{stdin} - "
    }
}

=== repometric/linterhub-cli/src/hub/colorguard/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "colorguard",
    "description": "CSS Colorguard helps you maintain the color set that you want, and warns you when colors you've added are too similar to ones that already exist.",
    "url": "https://github.com/SlexAxton/css-colorguard",
    "languages": [
        "css"
    ],
    "extensions": [
        "*.css"
    ],
    "license": "MIT",
    "areas": [
        "formatting"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "colorguard"
        }
    ],
    "postfix": " node file://{schema}/colorguard/reporter.js",
    "prefix": "node file://{schema}/colorguard/prefix.js ",
    "version": {
        "package": "1.2.0"
    },
    "defaults": {
        "--file": null,
        "": "*"
    },
    "stdin":
    {
        "available": false
    }
}

=== repometric/linterhub-cli/src/hub/sass-lint/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "sass-lint",
    "description": "A Node-only Sass linter for both sass and scss syntax!",
    "url": "https://github.com/sasstools/sass-lint",
    "languages": [
        "sass"
    ],
    "extensions": [
        "*.sass",
        "*.scss"
    ],
    "license": "MIT",
    "areas": [
        "syntax",
        "formatting"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "sass-lint"
        }
    ],
    "version": {
        "local": "1.10.2",
        "package": "1.10.2"
    },
    "postfix": " | node file://{schema}/sass-lint/reporter.js",
    "defaults": {
        "": "*",
        "--verbose": null,
        "--format": "json"
    },
    "stdin":
    {
        "available": false
    }
}

=== repometric/linterhub-cli/src/hub/standard/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "standard",
    "description": "JavaScript Standard Style",
    "url": "http://standardjs.com",
    "languages": [
        "javascript"
    ],
    "extensions": [
        "*.js"
    ],
    "license": "MIT",
    "areas": [
        "syntax"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "standard"
        }
    ],
    "version": {
        "local": "10.0.2",
        "package": "10.0.2"
    },
    "postfix": " | node file://{schema}/standard/reporter.js",
    "defaults": {
        "--verbose": null,
        "": "**/**/*.js"
    },
    "stdin":
    {
        "available": false
    }
}
